### ISSUE TITLE
Menambahkan Deskripsi Repositori dan Menggunakan Perbandingan Ketat

### ISSUE THREAD

**Issue by jefrydco** [glayOne23/webinar-vue-fundamental#1]
Hi Mas Hammam, terima kasih telah mengirimkan kode belajar Vue.js Fundamental, saya sangat mengapresiasi kerja keras Mas Hammam.

Mas juga telah menggunakan kerangka kerja Tailwind CSS untuk aplikasi pencari kata pada video YouTube ini. Luar biasa Mas!

Namun saya ada beberapa saran untuk kode yg Mas Kirim

1. Menambahkan Deskripsi Repositori
Agar repositori kita memiliki deskripsi, Mas bisa menambahkan berkas bernama `readme.md` di dalam direktori proyeknya Mas. Contohnya seperti ini Mas, https://github.com/jefrydco/jefrydco/blob/master/README.md

Hasilnya nanti akan seperti berikut:

![jefrydco](https://user-images.githubusercontent.com/20434351/89712748-0c804280-d9bd-11ea-8623-505f3e98fa15.png)

Pada berkas tersebut Mas juga dapat menuliskan deskripsi seputar aplikasi pada repo ini dan bagaimana cara menjalankannya. Mas dapat menggunakan penulisan [berformat markdown](https://guides.github.com/features/mastering-markdown/) atau HTML.

2. Menggunakan Perbandingan Ketat (_Strict Comparison_)
Pada berkas `index.html` pada baris ke 56 Mas melakukan pengecekan menggunakan simbol `==`. Simbol tersebut dalam JavaScript di namakan perbandingan longgar Mas atau _loose comparison_.

Saya menyarankan Mas untuk selalu menggunakan perbandingan ketat yg memiliki simbol `===` kapanpun. Hal tersebut mencegah adanya kesalahan perbandingan yg disebabkan oleh JavaScript.

Lebih lanjut mengenai perbandingan ketat dan perbandingan longgar, Mas dapat membaca pada tautan berikut, [Mozilla Developer Network - Equality Comparisons and Sameness](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness).

3. Menambahkan Spasi antara `()` dan `{` untuk Penamaan Fungsi
Masih pada berkas `index.html` baris ke 136 berikut:

https://github.com/glayOne23/webinar-vue-fundamental/blob/d06cbfa5419ca97f976e3c3a50e6e5065da77c74/index.html#L136

Saya menyarankan untuk menambahkan spasi antara `()` dan `{` Mas. Kurang lebih hasilnya akan seperti berikut:

```javascript
  methods: {
    // Kode yg lain
    ketikaPertamaDiKlik() {
      // Kode di dalamnya
    }
    // Kode yg lain
  }
```

Lebih lanjut mengenai gaya penulisan kode JavaScript dapat Mas baca pada tautan berikut, [Mozilla Developer Network - JavaScript Guidelines](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Code_guidelines/JavaScript#Use_expanded_syntax).

Semangat Mas! 😄

**Comment by glayOne23** [comment]
Terima kasih Mas Jefry yang sudah meluangkan waktu untuk mengoreksi kode
belajar Vue.js Fundamental saya. Baik mas, saran yang diberikan sangat
membantu dan saya terapkan. Dokumentasi yang diberikan juga sangat jelas
untuk membantu pembelajaran saya kedepannya.

Saya senang sekali bisa mengikuti webinar ini. Banyak sekali hal baru yang
saya pelajari mulai dari Vue dasar, tempat hosting, dan penulisan syntax
yang tepat.

Sukses selalu Mas Jefry 🙏

**Comment by jefrydco** [comment]
Terima kasih kembali Mas. Saya akan membiarkan isu ini terbuka ya Mas, nanti kalau Mas ada waktu dan berkenan memperbaiki isunya, Mas bisa menutup isu ini Mas. Terima kasih dan semangat selalu Mas! 😄

**Comment by glayOne23** [comment]
Baik Mas Jefry,  isu sudah saya perbaiki dan akan saya tutup 🙏. Terimakasih
